name: Generate feed and update server

on:
    # schedule:
    #    - cron:  '0 7 * * MON-FRI'
    #    - cron:  '45 6 * * MON-FRI'
    #    - cron:  '15 5 * * MON-FRI'
    #    - cron:  '30 9 * * THU'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name : Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-bs4 python3-dateutil
      - name : Set up SSH env
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_URL }} > ~/.ssh/known_hosts
      - name: Get feeds
        run: |
          python3 get_podcasts.py  ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} morning
          mkdir feeds
          mv *.xml feeds/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./feeds
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


